language: node_js

cache:
  directories:
  - $HOME/cache

node_js:
# Fails to compile module "ffi":
# error: no matching function for call to ‘v8::Object::ForceSet(v8::Local<v8::String>, v8::Local<v8::Value>, v8::PropertyAttribute)’
#- "node"
- "0.10"
- "0.12"
- "1"
- "2"
# Fails to compile module "nan":
# error: ‘class v8::Object’ has no member named ‘DefineOwnProperty’
#- "3"
- "4"
- "5"
- "6"
- "7"
- "8"

addons: {apt: {packages: [yasm, g++-4.8], sources: [ubuntu-toolchain-r-test]}}

# io.js v3+ requires C++11
before_install:
- export CXX="g++-4.8"

before_script:
- export CACHE_DIR="$HOME/cache"
- export CFLAGS="-I$CACHE_DIR/usr/include"
- export LDFLAGS="-L$CACHE_DIR/usr/lib"
- export LD_LIBRARY_PATH="$CACHE_DIR/usr/lib"
- export PKG_CONFIG_PATH="$CACHE_DIR/usr/lib/pkgconfig"
- tools/install-deps.sh > /dev/null
